theme: jekyll-theme-cayman
title: "欢迎来到恩卡尔的个人页面"
description: 在这里，您能认识一个不一样的恩卡尔
h1: 我的自我介绍
p: 我叫恩卡尔·努尔，哈萨克族，现在就读于北京大学，学习预防医学，来自新疆伊犁
h2:  book
p: 我喜欢以书会友，下面这些就是我这2019到2020这两年年读过的书
p: 中国文学：红楼梦，看见，亲爱的安德烈，活着，三体，等
p: 人文社科：通往奴役之路，简史三部曲，理想国，旧制度与大革命，乌合之众，娱乐至死，国富论，新教伦理和资本主义，等
p: 西方文学：悉达多，百年孤独，人类群星闪耀时，教父，使女的故事，包法利夫人，等 
